services:
  db:
    image: mysql:8 
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Welkom1234!
  
  oi-int: # OpenIddict
    build:
      context: ../Rsk.Samples.OpenIddict.AdminUI
      dockerfile: oi.Dockerfile
    expose:
      - "5003"
    environment:
      - DbProvider=MySql
      - ConnectionStrings__DefaultConnection=Server=db;Uid=root;Pwd=Welkom1234!;Database=OpenIddictDb;
      - ASPNETCORE_URLS=http://oi-int:5003      
    entrypoint: 
      - "/app/StartOpenIddict.sh"
      - "db" 
      - "3306"
      
  ui-int:
    build:
      context: ../AdminUI
    # Eventually, the dockerfile will build from an image. Currently we are building and publishing locally and the uiFromLocallyPublished.Dockerfile is simply copying the binaries onto the container.   
    #  dockerfile: ui.Dockerfile
      dockerfile: uiFromLocallyPublished.Dockerfile
    expose:
      - "5000"
    entrypoint: 
      - "/app/StartAdminUI.sh"
      - "oi-int" 
      - "5003"
    environment:
      - UiUrl=http://ui-int:5000
      - AuthorityUrl=http://oi-int:5003
      - IdentityConnectionString=Server=db;Uid=root;Pwd=Welkom1234!;Database=OpenIddictDb;
      - IdentityServerConnectionString=Server=db;Uid=root;Pwd=Welkom1234!;Database=OpenIddictDb;  # For now, for some reason, this cannot be blank
      - OpenIddictConnectionString=Server=db;Uid=root;Pwd=Welkom1234!;Database=OpenIddictDb;
      - LoggingOutputTemplate=[{"ui-int"} {Timestamp:dd-MM-yyyy HH:mm:ss} {Level}] {Message}{NewLine}{Exception}
      - DbProvider=SqlServer
      - LicenseKey=${DEMOLICENSEKEY}
      - ASPNETCORE_URLS=http://ui-int:5000
      - RequireHttpsMetadata=false
       
  ui-tests:
    build:
      context: .
      dockerfile: uiTests.Dockerfile
    volumes: 
      - ./log:/log # In this folder on host, map all in sub-folder named [logs] to a volume named [logs] in the root of the container. Create folders if not present.
    depends_on:
      - oi-int
      - ui-int