services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    ports: 
      - "1433:1433"
    container_name: mssql    
    environment:
      - MSSQL_SA_PASSWORD=Welkom1234#
      - ACCEPT_EULA=Y
   
  oi-int: # OpenIddict
    build:
      context: ../Rsk.Samples.OpenIddict.AdminUI
      dockerfile: oi.Dockerfile
    expose:
      - "5003"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;User Id=sa;Pwd=Welkom1234#;Database=OpenIddictDb;TrustServerCertificate=True;
      - DbProvider=SqlServer        
      - ASPNETCORE_URLS=http://oi-int:5003
#      - Logging__LogLevel__Default=Debug
#      - Logging__LogLevel__Microsoft=Debug
    entrypoint: 
      - "/app/StartOpenIddict.sh"
      - "db" 
      - "1433"
      
  ui-int:
    build:
      context: ../AdminUI
    # Eventually, the dockerfile will build from an image. Currently we are building and publishing locally and the uiFromLocallyPublished.Dockerfile is simply copying the binaries onto the container.   
    #  dockerfile: ui.Dockerfile 
      dockerfile: uiFromLocallyPublished.Dockerfile
    expose:
      - "5000"
    entrypoint: 
      - "/app/StartAdminUI.sh"
      - "oi-int" 
      - "5003"
    environment:
      - UiUrl=http://ui-int:5000
      - AuthorityUrl=http://oi-int:5003
      - IdentityConnectionString=Server=db,1433;User Id=sa;Pwd=Welkom1234#;Database=OpenIddictDb;TrustServerCertificate=True;
      - IdentityServerConnectionString=Server=db,1433;User Id=sa;Pwd=Welkom1234#;Database=OpenIddictDb;TrustServerCertificate=True;
      - OpenIddictConnectionString=Server=db,1433;User Id=sa;Pwd=Welkom1234#;Database=OpenIddictDb;TrustServerCertificate=True;
      - LoggingOutputTemplate=[{"ui-int"} {Timestamp:dd-MM-yyyy HH:mm:ss} {Level}] {Message}{NewLine}{Exception}
      - DbProvider=SqlServer
      - LicenseKey=${DEMOLICENSEKEY}
      - ASPNETCORE_URLS=http://ui-int:5000
      - RequireHttpsMetadata=false
      
  ui-tests:
    build:
      context: .
      dockerfile: uiTests.Dockerfile
    volumes: 
      - ./log:/log # In this folder on host, map all in sub-folder named [logs] to a volume named [logs] in the root of the container. Create folders if not present.
    depends_on:
      - oi-int
      - ui-int
